In [84]:
from tensorflow.keras.models import load_model
m1 = load_model("MobileNetV2.h5")
m2 = load_model("Inception.h5")
m3 = load_model("ResNet.h5")
m4 = load_model("VGG.h5")

In [36]:
from imutils import paths
import os
from tensorflow.keras.preprocessing.image import img_to_array
from tensorflow.keras.preprocessing.image import load_img
from tensorflow.keras.applications.resnet50 import preprocess_input

In [37]:
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [38]:
dataset="C:/Users/99sam/Desktop/GAIP/Project/Plant Disease Classification/Test/Test"
imagePaths=list(paths.list_images(dataset))


data=[]
data1=[]
data2=[]
labels=[]

for i in imagePaths:
    label=i.split(os.path.sep)[-2]
    labels.append(label)
    image=load_img(i,target_size=(224,224))
    image=img_to_array(image)
    data1.append(preprocess_input(image))
    image=image/255.0
    data.append(image)

In [39]:
from tensorflow.keras.applications.vgg16 import preprocess_input

In [40]:
for i in imagePaths:
    image=load_img(i,target_size=(224,224))
    image=img_to_array(image)
    data2.append(preprocess_input(image))

In [41]:
import numpy as np
data=np.array(data,dtype='float32')
data1=np.array(data1,dtype='float32')
data2=np.array(data2,dtype='float32')
labels=np.array(labels)
labels

array(['Healthy', 'Healthy', 'Healthy', 'Healthy', 'Healthy', 'Healthy',
       'Healthy', 'Healthy', 'Healthy', 'Healthy', 'Healthy', 'Healthy',
       'Healthy', 'Healthy', 'Healthy', 'Healthy', 'Healthy', 'Healthy',
       'Healthy', 'Healthy', 'Healthy', 'Healthy', 'Healthy', 'Healthy',
       'Healthy', 'Healthy', 'Healthy', 'Healthy', 'Healthy', 'Healthy',
       'Healthy', 'Healthy', 'Healthy', 'Healthy', 'Healthy', 'Healthy',
       'Healthy', 'Healthy', 'Healthy', 'Healthy', 'Healthy', 'Healthy',
       'Healthy', 'Healthy', 'Healthy', 'Healthy', 'Healthy', 'Healthy',
       'Healthy', 'Healthy', 'Powdery', 'Powdery', 'Powdery', 'Powdery',
       'Powdery', 'Powdery', 'Powdery', 'Powdery', 'Powdery', 'Powdery',
       'Powdery', 'Powdery', 'Powdery', 'Powdery', 'Powdery', 'Powdery',
       'Powdery', 'Powdery', 'Powdery', 'Powdery', 'Powdery', 'Powdery',
       'Powdery', 'Powdery', 'Powdery', 'Powdery', 'Powdery', 'Powdery',
       'Powdery', 'Powdery', 'Powdery', 'Powdery', 

In [42]:
values = list(labels)
print(values)
# integer encode
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
print(integer_encoded)
# binary encode
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)
# invert first example
inverted = label_encoder.inverse_transform([argmax(onehot_encoded[0, :])])
print(inverted)
target = np.array(onehot_encoded)

['Healthy', 'Healthy', 'Healthy', 'Healthy', 'Healthy', 'Healthy', 'Healthy', 'Healthy', 'Healthy', 'Healthy', 'Healthy', 'Healthy', 'Healthy', 'Healthy', 'Healthy', 'Healthy', 'Healthy', 'Healthy', 'Healthy', 'Healthy', 'Healthy', 'Healthy', 'Healthy', 'Healthy', 'Healthy', 'Healthy', 'Healthy', 'Healthy', 'Healthy', 'Healthy', 'Healthy', 'Healthy', 'Healthy', 'Healthy', 'Healthy', 'Healthy', 'Healthy', 'Healthy', 'Healthy', 'Healthy', 'Healthy', 'Healthy', 'Healthy', 'Healthy', 'Healthy', 'Healthy', 'Healthy', 'Healthy', 'Healthy', 'Healthy', 'Powdery', 'Powdery', 'Powdery', 'Powdery', 'Powdery', 'Powdery', 'Powdery', 'Powdery', 'Powdery', 'Powdery', 'Powdery', 'Powdery', 'Powdery', 'Powdery', 'Powdery', 'Powdery', 'Powdery', 'Powdery', 'Powdery', 'Powdery', 'Powdery', 'Powdery', 'Powdery', 'Powdery', 'Powdery', 'Powdery', 'Powdery', 'Powdery', 'Powdery', 'Powdery', 'Powdery', 'Powdery', 'Powdery', 'Powdery', 'Powdery', 'Powdery', 'Powdery', 'Powdery', 'Powdery', 'Powdery', 'Powdery'

In [82]:
def imp_stack(data,data1,data2):
    p1=m1.predict(data)
    p1=np.array(p1)
    p2=m2.predict(data)
    p2=np.array(p2)
    p3=m3.predict(data1)
    p3=np.array(p3)
    p4=m4.predict(data2)
    p4=np.array(p4)
    p_ans=(p1)+p2+p3+(p4)
    p_ans=np.argmax(p_ans,axis=1)
    return p_ans

In [44]:
pred = imp_stack(data,data1,data2)

5/5 [==============================] - 7s 1s/step


In [45]:
from sklearn.metrics import classification_report
print(classification_report(target.argmax(axis=1),pred))

              precision    recall  f1-score   support

           0       0.96      0.98      0.97        50
           1       0.98      0.96      0.97        50
           2       1.00      1.00      1.00        50

    accuracy                           0.98       150
   macro avg       0.98      0.98      0.98       150
weighted avg       0.98      0.98      0.98       150



In [46]:
p4=m4.predict(data2)
p4=np.argmax(p4,axis=1)
p4

5/5 [==============================] - 8s 2s/step


array([0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2,
       0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [47]:
p3=m3.predict(data1)
p3=np.argmax(p3,axis=1)
p3

5/5 [==============================] - 5s 938ms/step


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2,
       2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [48]:
print(classification_report(target.argmax(axis=1),p4))

              precision    recall  f1-score   support

           0       0.98      0.84      0.90        50
           1       0.98      0.92      0.95        50
           2       0.83      1.00      0.91        50

    accuracy                           0.92       150
   macro avg       0.93      0.92      0.92       150
weighted avg       0.93      0.92      0.92       150



In [49]:
print(classification_report(target.argmax(axis=1),p3))

              precision    recall  f1-score   support

           0       0.92      0.94      0.93        50
           1       0.98      0.92      0.95        50
           2       0.96      1.00      0.98        50

    accuracy                           0.95       150
   macro avg       0.95      0.95      0.95       150
weighted avg       0.95      0.95      0.95       150



In [50]:
p2=m2.predict(data)
p2=np.argmax(p2,axis=1)
p2

5/5 [==============================] - 3s 509ms/step


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 2, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [51]:
print(classification_report(target.argmax(axis=1),p2))

              precision    recall  f1-score   support

           0       0.94      0.92      0.93        50
           1       0.92      0.94      0.93        50
           2       0.98      0.98      0.98        50

    accuracy                           0.95       150
   macro avg       0.95      0.95      0.95       150
weighted avg       0.95      0.95      0.95       150



In [52]:
p1=m1.predict(data)
p1=np.argmax(p1,axis=1)
p1

5/5 [==============================] - 2s 292ms/step


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 0, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2], dtype=int64)

In [53]:
print(classification_report(target.argmax(axis=1),p1))

              precision    recall  f1-score   support

           0       0.89      0.98      0.93        50
           1       0.94      0.96      0.95        50
           2       1.00      0.88      0.94        50

    accuracy                           0.94       150
   macro avg       0.94      0.94      0.94       150
weighted avg       0.94      0.94      0.94       150



In [85]:
import tensorflow as tf
from tensorflow.keras.applications.resnet50 import preprocess_input
dataset="C:/Users/99sam/Desktop/Live"
imagePaths=list(paths.list_images(dataset))


data=[]
data1=[]
data2=[]
labels=[]

for i in imagePaths:
    label=i.split(os.path.sep)[-1]
    labels.append(label)
    image=load_img(i,target_size=(224,224))
    image=img_to_array(image)
    data1.append(preprocess_input(image))
    image=image/255.0
    data.append(image)

In [86]:
from tensorflow.keras.applications.vgg16 import preprocess_input
for i in imagePaths:
    image=load_img(i,target_size=(224,224))
    image=img_to_array(image)
    data2.append(preprocess_input(image))

In [87]:
import numpy as np
data=np.array(data,dtype='float32')
data1=np.array(data1,dtype='float32')
data2=np.array(data2,dtype='float32')
labels=np.array(labels)
labels

array(['Healthy_Leaf.jpg', 'Powdery_Leaf.jpg', 'Rust_Leaf.jpeg'],
      dtype='<U16')

In [88]:
values = list(labels)
print(values)
# integer encode
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
print(integer_encoded)
# binary encode
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)
# invert first example
inverted = label_encoder.inverse_transform([argmax(onehot_encoded[0, :])])
print(inverted)
target = np.array(onehot_encoded)

['Healthy_Leaf.jpg', 'Powdery_Leaf.jpg', 'Rust_Leaf.jpeg']
[0 1 2]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
['Healthy_Leaf.jpg']


In [89]:
pred = imp_stack(data,data1,data2)
pred

1/1 [==============================] - 1s 960ms/step


array([0, 1, 2], dtype=int64)

In [70]:
data

array([[[[-0.44972548, -0.37952548, -0.39191765],
         [-0.45364705, -0.38344705, -0.38799608],
         [-0.46149018, -0.3912902 , -0.3958392 ],
         ...,
         [-0.4732549 , -0.4265843 , -0.39976078],
         [-0.4732549 , -0.4265843 , -0.39976078],
         [-0.46541175, -0.43050587, -0.39976078]],

        [[-0.4458039 , -0.3756039 , -0.38799608],
         [-0.45364705, -0.38344705, -0.38799608],
         [-0.45756862, -0.38736862, -0.39191765],
         ...,
         [-0.46933332, -0.42266273, -0.3958392 ],
         [-0.46933332, -0.42266273, -0.3958392 ],
         [-0.46149018, -0.4265843 , -0.3958392 ]],

        [[-0.44972548, -0.37952548, -0.3840745 ],
         [-0.46149018, -0.3912902 , -0.3958392 ],
         [-0.46149018, -0.3912902 , -0.3958392 ],
         ...,
         [-0.46149018, -0.4265843 , -0.3958392 ],
         [-0.46541175, -0.41874117, -0.39191765],
         [-0.46541175, -0.41874117, -0.39191765]],

        ...,

        [[ 0.1777255 ,  0.26753333,  0

In [90]:
from sklearn.metrics import classification_report
print(classification_report(target.argmax(axis=1),pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         1
           1       1.00      1.00      1.00         1
           2       1.00      1.00      1.00         1

    accuracy                           1.00         3
   macro avg       1.00      1.00      1.00         3
weighted avg       1.00      1.00      1.00         3

